version: "2"
linters:
  enable:
    - bodyclose
    - dogsled
    - gochecknoinits
    - gocritic
    - gosec
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  disable:
    - dupl
    - gochecknoglobals
    - lll
  settings:
    errcheck:
      check-type-assertions: true
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - ifElseChain
    gocyclo:
      min-complexity: 25
    nakedret:
      max-func-lines: 15
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
